# apiVersion: v1
# kind: Namespace
# metadata:
#   name: staging
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-spring-boot-application
  # namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vulnerable-spring-boot-application
  template:
    metadata:
      labels:
        app: vulnerable-spring-boot-application
    spec:
      containers:
        - name: spring-boot-app
          image: 280398/vulnerable-spring-boot-application:{{tag}}
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: vulnerable-spring-boot-application
#  namespace: staging
spec:
 type: LoadBalancer
 selector:
   app: vulnerable-spring-boot-application
 ports:
   - protocol: TCP
     port: 80
     targetPort: 8080